export default {
  BarrancaAbajo: require("./../../Assets/Img/BarrancaAbajo.jpg"),
  Porfiado: require("./../../Assets/Img/Porfiado.jpg"),
  Raro: require("./../../Assets/Img/Raro.jpg"),
  Contacto: require("./../../Assets/Img/contactanos.jpg"),
  Mapas: require("./../../Assets/Img/mapasInteractivos2.png"),
  QuienesSomos: require("./../../Assets/Img/QuienesSomos.jpeg"),
  Logo: require("./../../Assets/Img/marca.jpg"),
  Marca: require("./../../Assets/Img/marca.svg"),
  IconoUsuario: require("./../../Assets/Img/IconoUsuario.png"),
  IconoHistorial: require("./../../Assets/Img/IconoHistoria.png"),
  IconoTelefono: require("./../../Assets/Img/IconoTelefono.jpg"),
  textura1: require("./../../Assets/Img/textura1.jpg"),
  textura2: require("./../../Assets/Img/textura2.jpg"),
  textura3: require("./../../Assets/Img/textura3.jpg"),
  textura4: require("./../../Assets/Img/textura4.jpeg"),
  textura5: require("./../../Assets/Img/textura5.jpg"),
  marca: require("./../../Assets/Img/marca.png"),
  marcaCuadrado: require("./../../Assets/Img/marcaCuadrado.png"),
  telBlanco: require("./../../Assets/Img/whitephone.png"),
  qr10: require("./../../Assets/Img/qr10.jpg"),
  qr20: require("./../../Assets/Img/qr20.jpg"),
  qr50: require("./../../Assets/Img/qr50.jpg"),
};
